# Generated by Django 4.2.3 on 2023-08-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUsTitle', models.CharField(max_length=100)),
                ('youtube_video_id', models.CharField(help_text='Youtube video code (e.g.,"httyAiqojjo")', max_length=100)),
                ('aboutUsDescription', models.TextField()),
                ('sideImage', models.ImageField(upload_to='about_us_banners/')),
                ('ourMission', models.TextField()),
                ('ourVision', models.TextField()),
                ('employedMembers', models.CharField(max_length=9)),
                ('completedTasks', models.CharField(max_length=12)),
                ('awardworn', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='accounting_and_finance_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='accounting_and_finance_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberImage', models.ImageField(upload_to='team/')),
                ('memberName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='audit_And_Non_Assurance_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='audit_And_Non_Assurance_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberImage', models.ImageField(upload_to='team/')),
                ('memberName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('blog_picture', models.ImageField(upload_to='blog_images/')),
                ('alt_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='business_Governance_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='business_Governance_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberImage', models.ImageField(upload_to='team/')),
                ('memberName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='company_secretarial_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='company_secretarial_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberImage', models.ImageField(upload_to='team/')),
                ('memberName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('office_time', models.CharField(help_text='office time  (e.g.,"10AM - 17PM")', max_length=15)),
                ('footer_description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('pinterest_link', models.URLField(blank=True)),
                ('video_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='sliderImage/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Consultancy_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Consultancy_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberImage', models.ImageField(upload_to='team/')),
                ('memberName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='management_Consulting_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='management_Consulting_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberImage', models.ImageField(upload_to='team/')),
                ('memberName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('mobile_contact', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam_AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberImage', models.ImageField(upload_to='team/')),
                ('memberName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAndBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/')),
            ],
        ),
        migrations.CreateModel(
            name='SlideDashboardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(help_text='The count number (e.g., "01.", "02.")', max_length=9)),
                ('text', models.CharField(help_text='The section title', max_length=30)),
                ('icon', models.CharField(choices=[('ti-user', 'User Icon'), ('flaticon-trophy', 'Trophy Icon'), ('flaticon-leadership', 'Leadership Icon')], help_text='The icon class name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='taxadvisory_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='taxadvisory_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberImage', models.ImageField(upload_to='team/')),
                ('memberName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('client_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('client_image', models.ImageField(upload_to='testimonials/')),
            ],
        ),
        migrations.CreateModel(
            name='Topbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
                ('vimeo_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('opening_time', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WhyYouUsFeature_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('flaticon-network-1', 'Network Icon 1'), ('flaticon-circular-label-with-certified-stamp', 'certified-stamp'), ('flaticon-chip', 'chip'), ('flaticon-24-hours', 'flaticon-24-hours')], help_text='Select an icon (e.g.,"flaticon-24-hours")', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
