# Generated by Django 4.2.3 on 2023-09-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_consulting', '0003_alter_footer_office_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidedashboardsection',
            name='count',
            field=models.CharField(help_text='The count number (e.g., "01.", "02.")', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='slidedashboardsection',
            name='text',
            field=models.CharField(help_text='The section title', max_length=30, null=True),
        ),
    ]
