# Generated by Django 4.2.3 on 2023-09-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_consulting', '0004_alter_slidedashboardsection_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidedashboardsection',
            name='count',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
